dist: xenial
language: go
services:
- mysql
- postgres
- redis-server
addons:
- postgresql: '9.4'
- sonarcloud:
    organization: yonikashi-github
    token:
      secure: V8oHshKgpiFWfZ/5KWYISlGl1BXxLVLxp7PPburn/miamSyLfIEhNBJh6TnJnLWBGRwmPzkOWjox5aXANmd6n208gGBiQ9M+FDspHy+2WxI+JvkKpiU1stqNxBNldZGnasMgfUy7Mz3tJpfU6hpg6ioTpdOd3LRXvL5+oCaOlZlWgeSyTgtJyaQAUztisN9lXD6v5x09+NM21Jf3MAyy1m9Xggec7p7CJ$
go:
- '1.8'
env:
  matrix: 
  global:
  - secure: V8oHshKgpiFWfZ/5KWYISlGl1BXxLVLxp7PPburn/miamSyLfIEhNBJh6TnJnLWBGRwmPzkOWjox5aXANmd6n208gGBiQ9M+FDspHy+2WxI+JvkKpiU1stqNxBNldZGnasMgfUy7Mz3tJpfU6hpg6ioTpdOd3LRXvL5+oCaOlZlWgeSyTgtJyaQAUztisN9lXD6v5x09+NM21Jf3MAyy1m9Xggec7p7CJWBhJWAEHvDFD5UiIyP1EQ7vheaHI0r3WKg0vrD05N+IC+5+O5XNtrGnzEfakP+actLYTYEP6DjdDHJHjntGpCgou43TKAFzhkj8HZxLbf0SnlvgTFSxPbIpkVWESp8zk/zb+54y6j2sZTWD21M1J93y0DwHG8RXJ4jZlbHckBjxO3Sz9YfPMcloD+oa7Sxcgm+hdoGWPx5eQwz9Z4Ro5+1iKhBJpTfDmNgTIxjn4mTRf+ck1ExvrDlDvNasLLfSR6u9hDHY4X00MEmTLWqd3LcGA7ZfHeH5VMjyz+sIpnuIh3PZN7Fx540FK6TCzW7Nj3mYpnAUAZQf5jSaax3l7sH0gTZin6oKLJgYlP4IW5KVTw6miYb0ONbO57ctR7rpefeQW04zv/HlVHe4/0nFXySqgPHyGel5+uheUchJdt2QS7KhEtmxRBLr3h6sIY6iqxdlerMKpXA=
  - secure: Aaif8IAeB+8D6OJS2Nva+hDZKzofx8FMrISNZW+SJhT1KSc36WsVBHnly3RgTgEZqVECws6nQc0USzD2uhjtf6lGCGwocw60m/TWaWZMn5vwKn0JLAtrdiyggtFTqDRlYrRQKlPGN007f3fSkG6H6KDljL4a/o03+qCNB7BUIUjKqOBFsqCrImblr+jZxh3T7dZOKUiRVWQRds2Gk3k4vwNXRh11lZr73/gZUP/MJJBK0mOTVa0/rBpDJ8hheEtx0tqK7r37Lr6YUFaVHWmTmCtOvNnhnyu+Sa1j4YmG2NVNzZBZcv5NJ5jFa8jPPZLbcAJ4WNx2GJaP+2ihC2pqQV+eASJUXzSttJJG5zGC/W6Ao4A3O5gnbw95MvkMsTTEyxE0HS/srAap9Ddw+HVircIGsFw7gLXnegsrhDs7rb15HePIsMIxCFosc+VDGksNMPDGBduwfVoYQWmuA12Yq1jzAo7I/ipGliQ5op1jOU0vi6LKP9jkHmY+ybGa419Jv84dNHpf3gXBRZ8bo8jmgNEFK/z3dZBu1DaTIu2hSBmk7yrW/40d7o4/QfRgQMr1nzZvQgw+oTf+dVZakMQPyARg16lvb2TbGGpQ9+lCKqlLv3nlZYwOHd18Qq0UqX6Ue7Dfb5tp3jq+kLEd73zLv2VR+AKM86ubAJaPa1RINJI=
go_import_path: github.com/kinecosystem/go
install:
- wget https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz
- tar -xzvf glide-v0.12.3-linux-amd64.tar.gz
- cp linux-amd64/glide $GOPATH/bin
script:
- glide install
- sonar-scanner
- "./support/scripts/run_tests"
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- go run ./support/scripts/build_release_artifacts/main.go
- "./support/scripts/push_snapshots_tag.sh"
matrix:
  fast_finish: false
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: Uhx8H2RFNsJ9GknDItSwhMOl5K3HTGNjifJwkLUiRio4JH4PzrkHDOzCOpEzrboviVF+Rch9VsC7HchIY2uyqeB9UW63dCMPeaYSs7rfNCmW8bTcGydeVOe0HV18mpM/4yPy/gsw5Zq+eGq7+p9NZtwkOHeQ/YtoSFcWbQQYs3CPZpBUP95KW1fGTn8OIW6nKkVA0Kyr6aXJFZB9AHIg24R9l2uraHdjg5EUJJO/4yR0GWC1pLTfUCqUt9mXPeGSQOhhvR+pCKSljY3pB6oex2hKH04u3U1iRzOBuKMPmMrcyJDzvVRkCaCn+0LPGZ3vgDDcDdcqYxEk1a1n27wzjqYlDeH4xaYTZGpB18LiX6MAm84+iviL5JILIMQ4NcqVNB2L37zl1UW+BMQUSH6+zQknHkGcOImU984PEdrhCM2uvknvp0+IGXdpyv9WwztzxhJOz6PAE1aA3O+BI1xuSft6sGY07Z0Q9iKO/uCWIHbsfLso16kIubiHzwjSAz90tbCc8VcR4EFeVqEoWm9QwRP0v6pclWMhj9bq3Oye1gKrSCwWPXCg8mRFCCuXgr4dev7I+vKcx43oIddgcx6vIROMYsgX/0gInBrkNxZw3Gu1YUXe1fuNvmCZWSlaWrO+9XWnFItnLs2ypnQjlguKzxgqmfqR0eXmMYBQrH18sxU=
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: q8H6HZWdaVF9lW2svzV/xdVZzF8SOBrnqGleAXEtI8l9bykq6gWBxSrU4BSma3KRsIBy/G5z6DNFGO0lRTPMLJ6j6WybvPruW1bOpBgPgaOD6Jz+jr62VNlRr4eWot+UZNTvuJMbR/3qqzMee5pIqIjI2kmDYD6VnOB0vAK3It/JCIc+VDDGzROMi9+nGIsAt7mZkU5kNzLDzaC+92IopTi7vXUGJ0cUDjKF1aiHKCFcWfkNUlTQoPnItpGNzBzGoTOX06LR9X+Uf9w651za+vZ7c0Ftd/Aujvv73KfMV5pIJehPCxI5x/PfEZ3AZwrDYC0theZ+NDWjHz/C2O56Ybi5V9TkKG3Yjy6eNVt7txhq1BY2A4EwvX8Lf8zMiG2VQ0YMNM1qUV6LDjqq4uCOeBjBjtgpqQXwMAtPKH+UF0Z8dj41+GfVOKD/Tv6r2Ue6XHYtk1pJVgWJwImnMbxNArEWWe2gt8ZL5vk21Q1VJN4bF2o2o94j/OjC/Nrawb9wgJN6tcXNEOYZGZPgoviJI5isBZy7SFzVXZpFgFEapZ7Ira3xa8bjGTmG+wTCWGkIRg1uX5EqbOqU1pP9lUPPknstfEi3w30ZR/4wnOrfXBh8fjfxZnTz6S32yolYxWKeSFyR6CvHvtZovAL7nEdEUb3DGSrfk+D6LcmzGqn78L4=
  file: dist/*
  file_glob: true
  overwrite: true
  prerelease: true
  tags: false
  name: Snapshots $(date --utc +'%F-%T')
  on:
    branch: master
    go: '1.9'
- provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: q8H6HZWdaVF9lW2svzV/xdVZzF8SOBrnqGleAXEtI8l9bykq6gWBxSrU4BSma3KRsIBy/G5z6DNFGO0lRTPMLJ6j6WybvPruW1bOpBgPgaOD6Jz+jr62VNlRr4eWot+UZNTvuJMbR/3qqzMee5pIqIjI2kmDYD6VnOB0vAK3It/JCIc+VDDGzROMi9+nGIsAt7mZkU5kNzLDzaC+92IopTi7vXUGJ0cUDjKF1aiHKCFcWfkNUlTQoPnItpGNzBzGoTOX06LR9X+Uf9w651za+vZ7c0Ftd/Aujvv73KfMV5pIJehPCxI5x/PfEZ3AZwrDYC0theZ+NDWjHz/C2O56Ybi5V9TkKG3Yjy6eNVt7txhq1BY2A4EwvX8Lf8zMiG2VQ0YMNM1qUV6LDjqq4uCOeBjBjtgpqQXwMAtPKH+UF0Z8dj41+GfVOKD/Tv6r2Ue6XHYtk1pJVgWJwImnMbxNArEWWe2gt8ZL5vk21Q1VJN4bF2o2o94j/OjC/Nrawb9wgJN6tcXNEOYZGZPgoviJI5isBZy7SFzVXZpFgFEapZ7Ira3xa8bjGTmG+wTCWGkIRg1uX5EqbOqU1pP9lUPPknstfEi3w30ZR/4wnOrfXBh8fjfxZnTz6S32yolYxWKeSFyR6CvHvtZovAL7nEdEUb3DGSrfk+D6LcmzGqn78L4=
  file: dist/*
  file_glob: true
  on:
    repo: stellar/go
    tags: true
    go: '1.9'
