dist: xenial
language: go
services:
- mysql
- postgres
- redis-server
addons:
  postgresql: '9.4'
go:
- '1.7'
- '1.8'
#- '1.9'
#- tip
go_import_path: github.com/kinecosystem/go
install:
- wget https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz
- tar -xzvf glide-v0.12.3-linux-amd64.tar.gz
- cp linux-amd64/glide $GOPATH/bin
script:
- glide list
- go env
- glide install
- ./support/scripts/run_tests
#- bash <curl -s https://codecov.io/bash) -t 4f651f20-82e1-4021-ac89-1cac21b92b0d

before_deploy:
- go run ./support/scripts/build_release_artifacts/main.go
- ./support/scripts/push_snapshots_tag.sh
matrix:
  fast_finish: false
#  allow_failures:
#  - go: tip
