#! /bin/bash
set -e

if [ "$CGO_ENABLED" = "1" ] 
then
    glide novendor | sed 's/^\./github.com\/kinecosystem\/go/g' | xargs -I {} -P 4 go test -race {}
else
    glide novendor | sed 's/^\./github.com\/kinecosystem\/go/g' | xargs -I {} -P 4 go test {}
fi
